// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeSeriesUploader.Infrastructure.Data;

#nullable disable

namespace TimeSeriesUploader.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeSeriesUploader.Domain.Entities.ResultRecord", b =>
                {
                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("AvgExecutionTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("AvgValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FirstExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("TimeDeltaSeconds")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.HasKey("FileName");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("TimeSeriesUploader.Domain.Entities.ValueRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ExecutionTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FileName", "Date");

                    b.ToTable("Values", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
